### ISSUE TITLE
Milestone 1.0 - Stable api & modularity

### ISSUE THREAD

**Issue by ocombe** [ocombe/ocLazyLoad#139]
- [x] Fix all the bug from 0.6.x

- [x] Make the lib modular:
  - [x] Externalize the loaders from the injector
  - [x] Externalize the polyfills
  - [x] Make the injector usable by other libs

- [x] Rewrite everything in ES6

- [x] Try to get as close as possible to 100% coverage

**Comment by lookfirst** [comment]
:+1:
