### ISSUE TITLE
Milestone 1.1 - Website & documentation

### ISSUE THREAD

**Issue by ocombe** [ocombe/ocLazyLoad#140]
- [ ] Make a website
  - [ ] Document the code with ng-docs
  - [ ] Extract the doc for the website using [dgeni](https://github.com/angular/dgeni)
  - [ ] Auto generate the website with the doc extracted by dgeni
