### ISSUE TITLE
Milestone 2.0 - Tools

### ISSUE THREAD

**Issue by ocombe** [ocombe/ocLazyLoad#141]
- [ ] Node module to create a tree of dependencies & a list of file routes
- [ ] Native support for SystemJS
- [ ] Module for Webpack

**Comment by lookfirst** [comment]
Sweet, if I can get rid of router.js in my project, that would be awesome sauce.

**Comment by IngenieroLata** [comment]
so... how is this going? just some days ago I was checking webpack with angular and found this. I though that ocLazyLoad was already supported. could it be great

**Comment by ocombe** [comment]
Actually it already works, you can find 2 examples on the subject here: https://oclazyload.readme.io/docs/webpack

**Comment by IngenieroLata** [comment]
ooo great! I'll check it out. Thanks!

**Comment by brutalcrozt** [comment]
@ocombe what is the verified current bug on 1.1 ?

**Comment by ocombe** [comment]
The opened issues tagged as "bug" and the ones not tagged that I need to check.
